### ISSUE TITLE
Unable to use load video script

### ISSUE THREAD

**Issue by vatsal278** [AliaksandrSiarohin/video-preprocessing#25]
(xx) PS E:\video-preprocessing-master> python load_videos.py --metadata vox-metadata.csv --format .png --out_folder vox --workers 1
0it [00:00, ?it/s]multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\anaconda\envs\xx\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "E:\video-preprocessing-master\load_videos.py", line 32, in run
    download(video_id.split('#')[0], args)
  File "E:\video-preprocessing-master\load_videos.py", line 25, in download
    video_path], stdout=DEVNULL, stderr=DEVNULL)
  File "D:\anaconda\envs\xx\lib\subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\anaconda\envs\xx\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "D:\anaconda\envs\xx\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "load_videos.py", line 100, in <module>
    for chunks_data in tqdm(pool.imap_unordered(run, zip(video_ids, args_list))):
  File "D:\anaconda\envs\xx\lib\site-packages\tqdm\_tqdm.py", line 1002, in __iter__
    for obj in iterable:
  File "D:\anaconda\envs\xx\lib\multiprocessing\pool.py", line 731, in next
    raise value
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by vatsal278** [comment]
PS E:\video-preprocessing-master> python load_videos.py --metadata vox-metadata.csv --format .png --out_folder vox --workers 1 --youtube-dl

Adding --youtube-dl add the library to path and helped me run the code.
