### ISSUE TITLE
cannot install requirements

### ISSUE THREAD

**Issue by lucascerro** [AliaksandrSiarohin/video-preprocessing#3]
when I run `pip install -r requirements.txt` I get the following error:
`Collecting cffi==1.11.5
  Using cached cffi-1.11.5.tar.gz (438 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\arquivos de programas (unprotected)\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Lucas\\AppData\\Local\\Temp\\pip-install-d5dssvmx\\cffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Lucas\\AppData\\Local\\Temp\\pip-install-d5dssvmx\\cffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Lucas\AppData\Local\Temp\pip-install-d5dssvmx\cffi\pip-egg-info'
         cwd: C:\Users\Lucas\AppData\Local\Temp\pip-install-d5dssvmx\cffi\
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Lucas\AppData\Local\Temp\pip-install-d5dssvmx\cffi\setup.py", line 120, in <module>
        if sys.platform == 'win32' and uses_msvc():
      File "C:\Users\Lucas\AppData\Local\Temp\pip-install-d5dssvmx\cffi\setup.py", line 98, in uses_msvc
        return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
      File "c:\arquivos de programas (unprotected)\python\lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "c:\arquivos de programas (unprotected)\python\lib\distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "c:\arquivos de programas (unprotected)\python\lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "c:\arquivos de programas (unprotected)\python\lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\arquivos de programas (unprotected)\python\lib\site-packages\setuptools\msvc.py", line 314, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "c:\arquivos de programas (unprotected)\python\lib\site-packages\setuptools\msvc.py", line 268, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

When I search for the error, I get a gazillion results on google, most proposing answers for Linux or MacOS, on a bunch of different installations. Been at this for the past 3 days and simply can't get past step 1.

**Comment by DanielAdelodun** [comment]
The error message says 

> Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

Have you tried that? The link in the error message is to download the Visual Studio IDE, but I think it's you can download just the build tools - https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by Jefersonwulf** [comment]
Lucas, como faço para entrar em contato contigo?

> when I run `pip install -r requirements.txt` I get the following error:
> `Collecting cffi==1.11.5 Using cached cffi-1.11.5.tar.gz (438 kB) ERROR: Command errored out with exit status 1: command: 'c:\arquivos de programas (unprotected)\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Lucas\\AppData\\Local\\Temp\\pip-install-d5dssvmx\\cffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Lucas\\AppData\\Local\\Temp\\pip-install-d5dssvmx\\cffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Lucas\AppData\Local\Temp\pip-install-d5dssvmx\cffi\pip-egg-info' cwd: C:\Users\Lucas\AppData\Local\Temp\pip-install-d5dssvmx\cffi\ Complete output (19 lines): Traceback (most recent call last): File "<string>", line 1, in <module> File "C:\Users\Lucas\AppData\Local\Temp\pip-install-d5dssvmx\cffi\setup.py", line 120, in <module> if sys.platform == 'win32' and uses_msvc(): File "C:\Users\Lucas\AppData\Local\Temp\pip-install-d5dssvmx\cffi\setup.py", line 98, in uses_msvc return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif') File "c:\arquivos de programas (unprotected)\python\lib\distutils\command\config.py", line 225, in try_compile self._compile(body, headers, include_dirs, lang) File "c:\arquivos de programas (unprotected)\python\lib\distutils\command\config.py", line 132, in _compile self.compiler.compile([src], include_dirs=include_dirs) File "c:\arquivos de programas (unprotected)\python\lib\distutils\_msvccompiler.py", line 360, in compile self.initialize() File "c:\arquivos de programas (unprotected)\python\lib\distutils\_msvccompiler.py", line 253, in initialize vc_env = _get_vc_env(plat_spec) File "c:\arquivos de programas (unprotected)\python\lib\site-packages\setuptools\msvc.py", line 314, in msvc14_get_vc_env return _msvc14_get_vc_env(plat_spec) File "c:\arquivos de programas (unprotected)\python\lib\site-packages\setuptools\msvc.py", line 268, in _msvc14_get_vc_env raise distutils.errors.DistutilsPlatformError( distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/ ---------------------------------------- ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`
> 
> When I search for the error, I get a gazillion results on google, most proposing answers for Linux or MacOS, on a bunch of different installations. Been at this for the past 3 days and simply can't get past step 1.

**Comment by lucascerro** [comment]
Just a note: I found this while trying to figure out the best way to install python. Maybe include the link as a resource?

https://docs.python-guide.org/

**Comment by Jefersonwulf** [comment]
> Just a note: I found this while trying to figure out the best way to install python. Maybe include the link as a resource?
> 
> https://docs.python-guide.org/

Lucas você tem algum meio de contato?

**Comment by lucascerro** [comment]
> 
> 
> > Just a note: I found this while trying to figure out the best way to install python. Maybe include the link as a resource?
> > https://docs.python-guide.org/
> 
> Lucas você tem algum meio de contato?

Olá, jefferson. Prefiro que você deixe um meio de contato! Pode ser aqui.

**Comment by lucascerro** [comment]
email?

> 
> 
> > > Just a note: I found this while trying to figure out the best way to install python. Maybe include the link as a resource?
> > > https://docs.python-guide.org/
> > 
> > 
> > Lucas você tem algum meio de contato?
> 
> Olá, jefferson. Prefiro que você deixe um meio de contato! Pode ser aqui.

email?

**Comment by Jefersonwulf** [comment]
Me manda um e-mail aqui jefersonlcpu@gmail.com
